import Head from 'next/head'
import HeaderComponent from '../components/Homepage/header-component'
import stylesHp from '../styles/Homepage/Homepage.module.css';
import {getAllHomepage, getHomepageById} from "../lib/Homepage/homepage-lib";
import Homepage from "../types/Homepage/homepage-type";
import FooterComponent from '../components/Homepage/footer-component';
import RecipeTeaserComponent from '../components/Recipe/recipeTeaser-component';
import Image from 'next/image'
import HeroBanner from '../components/Homepage/hero-banner';
import { HOMEPAGE_ID } from '../lib/Common/constants';

export async function getStaticProps({ preview = false}){
  const allHomepage = await getAllHomepage(preview);
  const homepage = await getHomepageById(HOMEPAGE_ID);
  return{
      props: {allHomepage,homepage, preview},
      // Next.js will attempt to re-generate the page:
      // - When a request comes in
      // - At most once every 10 seconds
      revalidate: 10, //in seconds
  }
  
}

type Props = {
  allHomepage: Homepage[];
  homepage: Homepage;
}

const Homepage = ({allHomepage,homepage}: Props) => {
 //const homepage = allHomepage[0];

  return (
    <div className={stylesHp.container}>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={stylesHp.main}>
        <HeaderComponent 
          allHeaders={homepage.header}
        />
        <HeroBanner 
          heroImageUrl={homepage.heroBanner?.results[0]?.fileUrl}
          altText=''
        />
       

        <div className={stylesHp.boxedContainer}>
          <h1 className={stylesHp.title}>
            {homepage.recipeTitle}
          </h1>
          <p className={stylesHp.SectionDescription}>{homepage.recipeSectionText}</p>
        
          <RecipeTeaserComponent
            allRecipes={allHomepage[0].recipes}
          />
        </div>

      
        <FooterComponent
          allFooters={homepage.footer}
        />
        
        
      </main>

      
    </div>
  )
}
export default Homepage;
