import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { CMS_NAME } from "../lib/constants";
import RecipeComponent from "../components/Recipe/recipe-component"; 
import Recipe from "../types/Recipes/recipe-type";
import {Media,MediaResults} from "../types/Basics/media-type";
import {getAllRecipes} from "../lib/recipe-lib";

export async function getStaticProps({ preview = false}){
    const allRecipes = await getAllRecipes(preview);
    return{
        props: {allRecipes, preview},
        // Next.js will attempt to re-generate the page:
        // - When a request comes in
        // - At most once every 10 seconds
        revalidate: 10, //in seconds
    }
}

type Props = {
    allRecipes: Recipe[];
}

const Recipes =({allRecipes}: Props) => {
    const recipePost = allRecipes[0];
    const recipePostImageUrl = recipePost.ImageList.results[0].fileUrl;

    const recipesAll = allRecipes.map;
    //const moreRecipes = allRecipes.slice(1);
    console.log("Recipe Title: " + recipePost.Title);
    console.log("Length: " + allRecipes.length + " + " + {allRecipes});
    console.log("Image: " + recipePostImageUrl);

  return (
    <div className={styles.container}>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Recipes from {CMS_NAME}
        </h1>
        <div className={styles.grid}>
        {allRecipes.map((recipe: any) => (
          <RecipeComponent
              recipeTitle={recipe.Title}
              id={recipe.id}
              name={recipe.Name}
              ingredients={recipe.Ingredients}
              minutesToPrepare={recipe.Duration}
              preparationDescription={recipe.Description}
              image={recipe.ImageList.results[0].fileUrl}
          />
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
};
export default Recipes;

